FROM php:8.2-apache
USER root
# Mise à jour et installation de Git, GNU Privacy Guard, Unzip et Zip
RUN apt-get update -qq && \
    apt-get upgrade -y && \
    apt-get install -qy \
    git \
    gnupg \
    unzip \
    zip \
    libssl-dev \
    pkg-config

# Installation de Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Installation des extensions PHP nécessaires
RUN docker-php-ext-install pdo pdo_mysql mysqli

# Installation de l'extension MongoDB via PECL
RUN pecl install mongodb && \
    docker-php-ext-enable mongodb

RUN echo "extension=mongodb.so" >> /usr/local/etc/php/php.ini

# Permet l'utilisation de htaccess
RUN a2enmod rewrite

EXPOSE 80

# Création d'un nouvel utilisateur non-root
RUN useradd -m -s /bin/bash monutilisateur

# Changement de propriétaire des fichiers de travail vers le nouvel utilisateur et changement des permissions
RUN chown -R monutilisateur:www-data /var/www/html \
    && chmod -R 775 /var/www/html

# Définit le propriétaire des fichiers et des répertoires dans /var/www/html/src
RUN chown -R monutilisateur:monutilisateur /var/www/html

# Exécution des commandes suivantes en tant que nouvel utilisateur non-root
USER monutilisateur